services:
  bot:
    build:
      context: .
      dockerfile: infra/images/Dockerfile.discord
    container_name: strava-bot
    ports:
      - "4000:4000"
    env_file:
      - apps/bot/.env
    depends_on:
      - postgres
    restart: on-failure:3

  webstrava:
    build:
      context: .
      dockerfile: infra/images/Dockerfile.webstrava
    container_name: webstrava
    ports:
      - "3000:3000"
    env_file:
      - apps/webstrava/.env
    depends_on:
      - postgres
    restart: no

  postgres:
    build:
      context: .
      dockerfile: infra/images/Dockerfile.postgres
    container_name: strava-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data: