FROM oven/bun:1-slim

WORKDIR /runstats

# Copy only package files first
COPY package.json bun.lock  ./
COPY packages/shared/package.json ./packages/shared/
COPY apps/bot/package.json ./apps/bot/

COPY apps/bot ./apps/bot
COPY packages/shared ./packages/shared

# Install dependencies
RUN bun install --filter '@apps/bot'

# Copy source files

# Build shared package
RUN cd packages/shared && bun run build

EXPOSE 4000

# Run bot
CMD ["bun", "run", "apps/bot/src/index.ts"]